# Site
# =====

baseurl: /semester_2019_winter

collections:
  tutorials:
    output: true
  workshops:
    output: true
  widgets:
    output: true

defaults:
- scope:
    path: ""
    type: "tutorials"
  values:
    layout: "tutorial"
    excerpt_separator: <!-- excerpt_end -->
    type: "tutorial"
- scope:
    path: ""
    type: "workshops"
  values:
    layout: "tutorial"
    type: "workshop"
    excerpt_separator: <!-- excerpt_end -->
    render_with_liquid: false

exclude:
- README.md
- LICENSE
- venv